apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/franktranvantu/kubernetes.git
    targetRevision: HEAD
    path: pods
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true